version: '2'

services:
  cli:
    tty: true
    image: hyperledger/fabric-tools:x86_64-1.0.0
    environment:
      - GOPATH=/opt/gopath
      - CORE_LOGGING_LEVEL=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - ../artifacts/orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
      - ../artifacts/chaincode:/opt/gopath/src/chaincode
      - ../artifacts/channels/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channels
      - ../logs/:/opt/gopath/src/github.com/hyperledger/fabric/peer/logs