version: '2'

# Top level network key specify the networks to be created
networks:
  provenance:
# Top level service keys
services:
  orderer.art.ifar.org:
    # Container name
    container_name: orderer.art.ifar.org
    # Public Heyperledger Fabric ARCH x86_64 version V1.0.0
    image: hyperledger/fabric-orderer:x86_64-1.0.0
    #Envirnoment varaibles for service container
    # - VAR:VAL
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/crypto/orderer/msp
      # to enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/crypto/orderer/tls/ca.crt, /var/hyperledger/crypto/peer0.egyptianmuseum/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    volumes:
    - ./artifacts/orderer/:/var/hyperledger/orderer
    - ./config/crypto-config/ordererOrganizations/art.ifar.org/orderers/orderer.art.ifar.org/:/var/hyperledger/crypto/orderer
    - ./config/crypto-config/peerOrganizations/egyptianmuseum.org/ca/root/:/var/hyperledger/crypto/peer0.egyptianmuseum
    # HOST_PORT:CONTAINER_PORT
    ports:
      - 7050:7050
    # Networks accessible to this container (orderer.art.ifar.org)  
    networks:
      - provenance

  peer0.egyptianmuseum.org:
    container_name: peer0.egyptianmuseum.org
    extends:
      file: ./config/peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.egyptianmuseum.org
      - CORE_PEER_LOCALMSPID=EGArtMSP
      - CORE_PEER_ADDRESS=peer0.egyptianmuseum.org:7051
      # - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.egyptianmuseum.org:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.egyptianmuseum.org:7051
    volumes:
      - ./config/crypto-config/peerOrganizations/egyptianmuseum.org/peers/peer0.egyptianmuseum.org/:/etc/hyperledger/crypto/peer
      # - ./config/crypto-config/peerOrganizations/egyptianmuseum.org/peers/peer0.egyptianmuseum.org/tls/:/etc/hyperledger/crypto/peer/tls
    ports:
         - 7051:7051
         - 7053:7053
    depends_on:
      - orderer.art.ifar.org
    networks:
      - provenance

  # peer1.egyptianmuseum.org:
  #   container_name: peer1.egyptianmuseum.org
  #   extends:
  #     file: ./config/peer.yaml
  #     service: peer
  #   environment:
  #     - CORE_PEER_ID=peer1.egyptianmuseum.org
  #     - CORE_PEER_ADDRESS=peer1.egyptianmuseum.org:7051
  #     - CORE_PEER_LOCALMSPID=EGArtMSP
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.egyptianmuseum.org:7051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.egyptianmuseum.org:7051
  #   volumes:
  #     - ./config/crypto-config/peerOrganizations/egyptianmuseum.org/peers/peer1.egyptianmuseum.org/msp:/etc/hyperledger/msp
  #     - ./config/crypto-config/peerOrganizations/egyptianmuseum.org/peers/peer1.egyptianmuseum.org/tls:/etc/hyperledger/fabric/tls
  #   ports:
  #        - 8051:7051
  #        - 8053:7053
  #   depends_on:
  #     - orderer.art.ifar.org
  #     - peer0.egyptianmuseum.org
  #   networks:
  #     - provenance 

  # peer0.louvre.fr:
  #   container_name: peer0.louvre.fr
  #   extends:
  #     file: ./config/peer.yaml
  #     service: peer
  #   environment:
  #     - CORE_PEER_ID=peer0.louvre.fr
  #     - CORE_PEER_ADDRESS=peer0.louvre.fr:7051
  #     - CORE_PEER_LOCALMSPID=FRArtMSP
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.louvre.fr:7051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.louvre.fr:7051
  #   volumes:
  #     - ./config/crypto-config/peerOrganizations/louvre.fr/peers/peer0.louvre.fr/msp:/etc/hyperledger/msp
  #     - ./config/crypto-config/peerOrganizations/louvre.fr/peers/peer0.louvre.fr/tls:/etc/hyperledger/fabric/tls
  #   ports:
  #        - 9051:7051
  #        - 9053:7053
  #   depends_on:
  #     - orderer.art.ifar.org
  #   networks:
  #     - provenance

  # peer1.louvre.fr:
  #   container_name: peer1.louvre.fr
  #   extends:
  #     file: ./config/peer.yaml
  #     service: peer
  #   environment:
  #     - CORE_PEER_ID=peer1.louvre.fr
  #     - CORE_PEER_ADDRESS=peer1.louvre.fr:7051
  #     - CORE_PEER_LOCALMSPID=FRArtMSP
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.louvre.fr:7051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.louvre.fr:7051
  #   volumes:
  #     - ./config/crypto-config/peerOrganizations/louvre.fr/peers/peer1.louvre.fr/msp:/etc/hyperledger/msp/peer
  #     - ./config/crypto-config/peerOrganizations/louvre.fr/peers/peer1.louvre.fr/tls:/etc/hyperledger/fabric/tls
  #   ports:
  #        - 10051:7051
  #        - 10053:7053
  #   depends_on:
  #     - orderer.art.ifar.org
  #   networks:
  #     - provenance

  # # peer0.bauhaus.de:
  # #   container_name: peer0.bauhaus.de
  # #   extends:
  # #     file: ./peer.yaml
  # #     service: peer
  # #   environment:
  # #     - CORE_PEER_ID=peer0.bauhaus.de
  # #     - CORE_PEER_ADDRESS=peer0.bauhaus.de:7051
  # #     - CORE_PEER_LOCALMSPID=DEArtMSP
  # #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bauhaus.de:7051
  # #   volumes:
  # #     - ./crypto-config/peerOrganizations/bauhaus.de/peers/peer0.bauhaus.de/msp:/etc/hyperledger/msp/peer
  # #   ports:
  # #        - 10051:7051
  # #        - 10053:7053
  # #   depends_on:
  # #     - orderer.art.ifar.org
  # #   networks:
  # #     - provenance

  cli0.egyptianmuseum.org:
    extends:
      file: ./config/cli.yaml
      service: cli
    container_name: cli0.egyptianmuseum.org
    environment:
      - CORE_PEER_ID=cli0.egyptianmuseum.org
      - CORE_PEER_ADDRESS=peer0.egyptianmuseum.org:7051
      - CORE_PEER_LOCALMSPID=EGArtMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/users/Admin@egyptianmuseum.org/msp
    volumes:
      - ./config/crypto-config/peerOrganizations/egyptianmuseum.org/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.art.ifar.org
      - peer0.egyptianmuseum.org
    networks:
      - provenance

  # cli1.egyptianmuseum.org:
  #   extends:
  #     file: ./config/cli.yaml
  #     service: cli
  #   container_name: cli1.egyptianmuseum.org
  #   environment:
  #     - CORE_PEER_ID=cli1.egyptianmuseum.org
  #     - CORE_PEER_ADDRESS=peer1.egyptianmuseum.org:7051
  #     - CORE_PEER_LOCALMSPID=EGArtMSP
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@egyptianmuseum.org/msp
  #   volumes:
  #     - ./config/crypto-config/peerOrganizations/egyptianmuseum.org:/etc/hyperledger/msp
  #   depends_on:
  #     - orderer.art.ifar.org
  #     - peer1.egyptianmuseum.org
  #   networks:
  #     - provenance

  # cli0.louvre.fr:
  #   extends:
  #     file: ./config/cli.yaml
  #     service: cli
  #   container_name: cli0.louvre.fr
  #   environment:
  #     - CORE_PEER_ID=cli0.louvre.fr
  #     - CORE_PEER_ADDRESS=peer0.louvre.fr:7051
  #     - CORE_PEER_LOCALMSPID=FRArtMSP
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@louvre.fr/msp
  #   volumes:
  #     - ./config/crypto-config/peerOrganizations/louvre.fr:/etc/hyperledger/msp
  #   depends_on:
  #     - orderer.art.ifar.org
  #     - peer0.louvre.fr
  #   networks:
  #     - provenance

  # cli1.louvre.fr:
  #   extends:
  #     file: ./config/cli.yaml
  #     service: cli
  #   container_name: cli1.louvre.fr
  #   environment:
  #     - CORE_PEER_ID=cli1.louvre.fr
  #     - CORE_PEER_ADDRESS=peer1.louvre.fr:7051
  #     - CORE_PEER_LOCALMSPID=FRArtMSP
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@louvre.fr/msp
  #   volumes:
  #     - ./config/crypto-config/peerOrganizations/louvre.fr:/etc/hyperledger/msp
  #   depends_on:
  #     - orderer.art.ifar.org
  #     - peer1.louvre.fr
  #   networks:
  #     - provenance

  # cli.bauhaus.de:
  #   extends:
  #     file: ./cli.yaml
  #     service: cli
  #   container_name: cli.bauhaus.de
  #   environment:
  #     - CORE_PEER_ID=cli.bauhaus.de
  #     - CORE_PEER_ADDRESS=peer0.bauhaus.de:7051
  #     - CORE_PEER_LOCALMSPID=DEArtMSP
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@bauhaus.de/msp
  #   volumes:
  #     - ./crypto-config/peerOrganizations/bauhaus.de:/etc/hyperledger/msp
  #   depends_on:
  #     - orderer.art.ifar.org
  #     - peer0.bauhaus.de
  #   networks:
  #     - provenance

  # ca.louvre:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
  #     - FABRIC_CA_SERVER_CA_NAME=ca.louvre
  #   ports:
  #     - "9054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/louvre.fr/ca/root/:/etc/hyperledger/fabric-ca-server-config
  #   container_name: ca.louvre
  #   networks:
  #     - provenance

  # ca.egyptianmuseum:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
  #     - FABRIC_CA_SERVER_CA_NAME=ca.egyptianmuseum
  #   ports:
  #     - "8054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/egyptianmuseum.org/ca/root/:/etc/hyperledger/fabric-ca-server-config
  #   container_name: ca.egyptianmuseum
  #   networks:
  #     - provenance

  # ca.bauhaus:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
  #     - FABRIC_CA_SERVER_CA_NAME=ca.bauhaus
  #   ports:
  #     - "10054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/bauhaus.de/ca/root/:/etc/hyperledger/fabric-ca-server-config
  #   container_name: ca.bauhaus
  #   networks:
  #     - provenance

  # client.egyptianmuseum:
  #   tty: true
  #   image: hyperledger/fabric-ca
  #   container_name: client.egyptianmuseum
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #   volumes:
  #     - ./crypto-config/peerOrganizations/egyptianmuseum.org/users/:/etc/hyperledger/fabric-ca-client
  #   depends_on:
  #     - ca.egyptianmuseum
  #   command: sh -c 'sleep 5;fabric-ca-client enroll -u http://admin:adminpw@ca.egyptianmuseum:7054;sleep 10000'
  #   networks:
  #    - provenance
